### ISSUE TITLE
Error when NA is passed in limits for y axis

### ISSUE THREAD

**Issue by rcalinjageman** [eclarke/ggbeeswarm#42] opened 2019-05-29 15:15 UTC
I am encountering an issue when using ggbeeswarm and setting NA for limits on the y_axis.  

Here's the code that reproduces the problem

```
library(ggplot2)
library(ggbeeswarm)
myplot <- ggplot(iris, aes(x=Species, y=Sepal.Length)) + scale_y_continuous(limits = c(0,NA)) + geom_beeswarm()
myplot
```
And this gives:
```
Error in if (limDiff == 0) limDiff <- 1 : 
  missing value where TRUE/FALSE needed
```

If I switch to:
`myplot <- ggplot(iris, aes(x=Species, y=Sepal.Length)) + scale_y_continuous(limits = c(0,10)) + geom_beeswarm()
`
then the plot renders correctly

**Comment by sherrillmix** [comment] 2019-08-12 18:30
Sorry somehow I didn't notice this issue until now. I can't seem to replicate it currently (i.e. `ggplot(iris, aes(x=Species, y=Sepal.Length)) + scale_y_continuous(limits = c(0,NA)) + geom_beeswarm()` runs without an error) so I wonder if whatever was causing the issue has been fixed in the meantime. Is it still causing problems for you?

**Comment by sherrillmix** [comment] 2019-08-14 20:42
I should clarify that I could replicate the problem in v0.6.0 but the current github version appears to have fixed this (there was a major rewrite of beeswarm code). Let me know know if the problem is still there for you in the current version.

**Closed by sherrillmix** 2019-08-14 20:42 UTC
